apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-bigtable-connector
  namespace: base-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-bigtable-connector
  template:
    metadata:
      labels:
        app: nats-bigtable-connector
    spec:
      serviceAccountName: nats-bigtable-connector-ksa
      tolerations:
      - key: "cloud.google.com/compute-class"
        operator: "Equal"
        value: "Scale-Out"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.arch | default "arm64" }}
              - key: cloud.google.com/compute-class
                operator: In
                values:
                - Scale-Out
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: cloud.google.com/machine-family
                    operator: In
                    values:
                      - n4a
            - weight: 90
              preference:
                matchExpressions:
                  - key: cloud.google.com/machine-family
                    operator: In
                    values:
                      - c4a
            - weight: 80
              preference:
                matchExpressions:
                  - key: cloud.google.com/machine-family
                    operator: In
                    values:
                      - t2a
      containers:
        - name: connector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-c", "/config/config.yaml"]
          env:
            - name: NATS_USER
              valueFrom:
                secretKeyRef:
                  name: nats-bigtable-connector-secret
                  key: NATS_USER
            - name: NATS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nats-bigtable-connector-secret
                  key: NATS_PASSWORD
            - name: NATS_HOST
              valueFrom:
                secretKeyRef:
                  name: nats-bigtable-connector-secret
                  key: NATS_HOST
          volumeMounts:
            - name: connector-config-volume
              mountPath: /config
            - name: connector-proto-volume
              mountPath: /proto/telemetry.proto
              subPath: telemetry.proto
      volumes:
        - name: connector-config-volume
          configMap:
            name: nats-bigtable-connector-config
        - name: connector-proto-volume
          configMap:
            name: nats-bigtable-connector-proto
